### ISSUE TITLE
USER STORY:<View recipe details>

### ISSUE THREAD

**Issue by NatasaMiric** [NatasaMiric/feedme#12]
As a **user** I can **view the details of a single recipe** so that **I can learn more about it** NatasaMiric/feedme-api#3 

### Acceptance criteria 
* user can see a single recipe details

### Tasks
- [x] Create Recipe Detail Page Component
- [x] Fetch recipe data from API 
- [x] Create Recipe Component
