### ISSUE TITLE
USER STORY:<Read recipe comments>

### ISSUE THREAD

**Issue by NatasaMiric** [NatasaMiric/feedme#20]
As a **user** I can **read comments on the recipe** so that **I can read what other users think about the recipe** NatasaMiric/feedme-api#8 

### Aceptance criteria 

* user should be able to read all comment on posted recipe

### Tasks
- [x] Create comment component
- [x] Add comment component on RecipeDetail Page where  the comments should be
- [x] create array for displaying the comments
