### ISSUE TITLE
USER STORY:<Sign Up>

### ISSUE THREAD

**Issue by NatasaMiric** [NatasaMiric/feedme#6]
As a user I can create a new account so that I can access all the features for signed-up users NatasaMiric/feedme-api#1 

### Acceptance criteria
* user is able to input a username and password
* user is able to press sign up button
* The account is created and user is redirected to sign-in page
* user gets error messages in case of invalid input

### Tasks

- [x] Create Sign up component
- [x] Add custom css
- [x] Add event listeners
- [x] Test
