### ISSUE TITLE
USER STORY:<Logged in status>

### ISSUE THREAD

**Issue by NatasaMiric** [NatasaMiric/feedme#7]
As a user, I can tell if I am logged in or not so that I can log in if I need to NatasaMiric/feedme-api#1 

### Acceptance criteria 
* change icons based on logged-in state

### Tasks
- [x] Create custom Context file to hold the logic for current user state
- [x] Send a request to API to check who is currently logged in
- [x] Add current user provider in index.js
- [x] Call custom hook in sign in form and navbar

 
- [x] Test
