### ISSUE TITLE
USER STORY:<Sign In>

### ISSUE THREAD

**Issue by NatasaMiric** [NatasaMiric/feedme#8]
As a user, I can sign in to the app so that I can access functionality for logged-in users NatasaMiric/feedme-api#1 

### Acceptance criteria
* user is able to input his username and password
* user is able to click on submit button 
* user is logged in after clicking on submit button and redirected to home page

### Tasks 
- [x] Create a Sign in component
- [x] Add custom CSS
- [x] Add event handlers
- [x] Add error handling
- [x] Test
