### ISSUE TITLE
USER STORY: Maintain logged-in status 

### ISSUE THREAD

**Issue by NatasaMiric** [NatasaMiric/feedme#9]
As a **registered user** I can **maintain my logged-in status until I choose to log out** so that **my user experience is not compromised**  NatasaMiric/feedme-api#1 

### Acceptance criteria
* user stays logged in for 24h

### Tasks
- [x] create axios interceptors axiosRes and axiosReq
- [x] set axiosReq to refresh the access token if it gets a 401 error
- [x] add axiosRes to handle mount function
- [x] set axiosReq always to refresh the access token before a request
